FROM gradle:7.2.0-jdk17 as compiler
COPY . /home/source/java
WORKDIR /home/source/java
USER root
RUN chown -R gradle /home/source/java
USER gradle
RUN ./gradlew clean build -x test

FROM openjdk:17-slim
COPY --from=compiler "/home/source/java/build/libs/spring-native-image-0.0.1-SNAPSHOT.jar" app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
